  version: '3.8'

  services:
    db:
      image: postgres:latest
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: galiphone
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"

  volumes:
    pgdata:
      driver: local
